workspace:
  base: /drone/workspace
  path: /service-in2-gateway

pipeline:
  build:
    image: node
    pull: true
    commands:
      - npm install
      - npm run build
    when:
      branch: [ feature/*, test/feature/*, demo/feature/*, master ]
  ship:
    image: node
    pull: true
    commands:
      - env
      - profzone ship --push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [ feature/*, test/feature/*, demo/feature/*, master ]
  deploy-staging:
    image: node
    pull: true
    commands:
      - profzone deploy --env STAGING
    when:
      branch: [ feature/* ]
  deploy-test:
    image: node
    pull: true
    commands:
      - profzone deploy --env TEST
    when:
      branch: [ test/feature/* ]
  deploy-demo:
    image: node
    pull: true
    commands:
      - profzone deploy --env DEMO
    when:
      branch: [ demo/feature/* ]
  deploy-master:
    image: node
    pull: true
    commands:
      - profzone deploy --env STAGING
    #      - profzone deploy --env TEST
    #      - profzone deploy --env DEMO
    when:
      branch: [ master ]
